# Generated by Django 4.2.25 on 2025-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('article_body', models.TextField()),
                ('date_written', models.DateTimeField(auto_now_add=True)),
                ('approved', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('blurb', models.TextField(blank=True)),
                ('when_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
