# Generated by Django 4.2.25 on 2025-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0002_article_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ready_for_approval',
            field=models.IntegerField(choices=[(0, 'Not Ready For Approval'), (1, 'Ready For Approval')], default=0),
        ),
    ]
