# Generated by Django 4.2.25 on 2025-11-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='blurb',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
